services:
  - type: web
    name: ai-ads-ugc-server
    env: node
    plan: free
    buildCommand: npm install
    preDeployCommand: npm run prisma:generate && npm run prisma:migrate:deploy
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "25.4.0"
